# Generated by Django 3.0.7 on 2020-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('webamcarts', '0002_cartwomen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartkids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('productkids', models.ManyToManyField(to='products.ProductKids')),
            ],
        ),
    ]
