# Generated by Django 3.0.7 on 2020-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200709_1801'),
        ('webamcarts', '0008_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='products.Variation'),
        ),
    ]
